### ISSUE TITLE
Problem with compile

### ISSUE THREAD

**Issue by CreativeZoller** [noreading/bootstrap5-webpack-boilerplate#1]
I just cloned this and wanted to test. Unfortunately not a single script is available after compile. I tried to include the BS scripts manually in the plugins part with `new webpack.ProvidePlugin()`, still nothing.
I manually modified the scripts for my liking:
```
  "scripts": {
    "build": "webpack --config webpack.config.js --mode production",
    "dev": "webpack serve --config webpack.config.js --mode development --port 8080"
  },
```
And here are my packages, if that helps:
```
    "@babel/core": "^7.14.3",
    "@babel/preset-env": "^7.14.2",
    "@popperjs/core": "^2.9.2",
    "autoprefixer": "^10.2.5",
    "babel-loader": "^8.2.2",
    "bootstrap": "^5.0.1",
    "css-loader": "^5.2.4",
    "dotenv-webpack": "^7.0.2",
    "exports-loader": "^3.0.0",
    "fast-glob": "^3.2.5",
    "mime-types": "^2.1.30",
    "mini-css-extract-plugin": "^1.6.0",
    "node-sass": "^6.0.0",
    "path": "^0.12.7",
    "postcss": "^8.2.15",
    "postcss-loader": "^5.3.0",
    "postcss-preset-env": "^6.7.0",
    "sass-loader": "^11.1.1",
    "sharp": "^0.28.2",
    "style-loader": "^2.0.0",
    "trash": "^7.1.1",
    "uglifyjs-webpack-plugin": "^2.2.0",
    "webpack": "^5.37.1",
    "webpack-cli": "^4.7.0",
    "webpack-dev-server": "^3.11.2"
```
Of course, my versions are the following:
Node - 14.15..4
NPM - 7.11.2

Any ideas about why is could not compile with the Bootstrap scripts?

Or it is a known issue just left out from the readme by accident?

**Comment by noreading** [comment]
I tested it with Node 14.17.0 and 6.14.13.
I also updated the packages now, so you can try again, if there's an issue with any package in your specific setup.

What do you mean by `not a single script is available after compile`? Webpack doesn't compile any JS or CSS file into the `/dist/` folder?

**Comment by noreading** [comment]
Closed due to lack of details.
