### ISSUE TITLE
Problem with npm run images

### ISSUE THREAD

**Issue by jonnydevv** [noreading/bootstrap5-webpack-boilerplate#157]
Hello,
When i run `npm run images` i get and error due to the use of require instead of import with `trash` package:
```
/var/www/bootstrap5-webpack-boilerplate/bin/images.js:12
const trash = require("trash");
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /var/www/bootstrap5-webpack-boilerplate/node_modules/trash/index.js from /var/www/bootstrap5-webpack-boilerplate/bin/images.js not supported.
Instead change the require of index.js in /var/www/bootstrap5-webpack-boilerplate/bin/images.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/var/www/bootstrap5-webpack-boilerplate/bin/images.js:12:15) {
  code: 'ERR_REQUIRE_ESM'
}
```
If i change to import and set  type to module, i get another error.
How can it be fixed?

Using:
node: v16.14.0
npm: 8.13.2

**Comment by noreading** [comment]
Thanks for posting your issue.

I just released version 2, including hot reloading, etc. that also uses newer packages and imports.
Please try if the same issue occurs with the new version. If it does, i'll check that case again.
