### ISSUE TITLE
vite js instead webpack and tailwindcss  instead bootstrap?

### ISSUE THREAD

**Issue by zulfikopfstand** [noreading/bootstrap5-webpack-boilerplate#65]
hi Dominik, super Idee und sehr effizient die Repository.

**Comment by noreading** [comment]
Thanks for your comment. There's a good reason to still have a Bootstrap boilerplate, as for quick and easy projects tailwind can take mor time. Tailwind is a nice tool, but as I'm not developing many "plain" websites myself, I can't add more repositories for other frameworks than Bootstrap yet.
